spring:
  application:
    name: comments-service

  jpa:
    generate-ddl: false
    show-sql: true
  properties:
    hibernate:
      search:
        backend:
          type: lucene
          directory.root: ./data/index

  liquibase:
    change-log: db.changelog/changelog-master.xml
    enabled: true
server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    ru.clevertec: debug
  file:
    name: ./logs/log-file.log


cache:
  capacity: 10
  type: LRU


---
spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/news_system
  feign:
    client:
      news-service:
        name: news-service
        url: "http://localhost:8081"

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://news-db:5432/news_system
    username: postgres
    password: postgres
  feign:
    client:
      news-service:
        name: news-service
        url: "http://news-service:8081"

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://news-db:5432/news_system_test
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db.changelog/changelog-test.xml
  feign:
    client:
      news-service:
        name: news-service
        url: "http://localhost:8081"
