spring:
  application:
    name: comments-service

  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/news_system

  liquibase:
    change-log: db.changelog/changelog-master.xml
server:
  port: 8082


feign:
  client:
    news:
      name: news
      url: "http://localhost:8081"