spring:
  application:
    name: news-service

  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/news_system
  properties:
    hibernate:
      search:
        backend:
          type: lucene
          directory.root: ./data/index

  liquibase:
    change-log: db.changelog/changelog-master.xml
server:
  port: 8081

feign:
  client:
    news:
      name: comments
      url: "http://localhost:8082"